import hashlib
import json
import re
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

from datasets import load_dataset

SOURCE_URL = "https://huggingface.co/datasets/wikimedia/wikipedia"
LICENSE_TAG = "CC-BY-SA-3.0"

SENTENCE_SPLIT = re.compile(r'[\n।]+')
MIN_SENTENCE_CHARS = 20
MAX_SENTENCE_CHARS = 400
TELUGU_START = 0x0C00
TELUGU_END = 0x0C7F


def _is_mostly_telugu(text: str, threshold: float = 0.4) -> bool:
    if not text:
        return False
    te = sum(1 for c in text if TELUGU_START <= ord(c) <= TELUGU_END)
    return te / len(text) >= threshold


def _row_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _extract_sentences(article_text: str) -> list[str]:
    sentences = []
    for sent in SENTENCE_SPLIT.split(article_text):
        sent = sent.strip()
        if MIN_SENTENCE_CHARS <= len(sent) <= MAX_SENTENCE_CHARS and _is_mostly_telugu(sent):
            sentences.append(sent)
    return sentences


def main() -> None:
    today = datetime.now(tz=timezone.utc).strftime("%Y%m%d")
    pull_ts = datetime.now(tz=timezone.utc).isoformat()
    output_file = Path(f"data/raw/wikipedia_te_{today}.jsonl")
    manifest_file = Path(f"data/manifests/wikipedia_te_{today}_manifest.json")

    if output_file.exists():
        print(f"Snapshot {output_file} already exists — raw/ is immutable, skipping.")
        sys.exit(0)

    output_file.parent.mkdir(parents=True, exist_ok=True)
    manifest_file.parent.mkdir(parents=True, exist_ok=True)

    print("Loading Telugu Wikipedia via datasets library (all 87k articles) ...")
    ds = load_dataset("wikimedia/wikipedia", "20231101.te", split="train")
    print(f"  {len(ds):,} articles loaded")

    articles_processed = sentences_written = 0

    with output_file.open("w", encoding="utf-8") as fout:
        for row in ds:
            article_id = str(row.get("id", uuid.uuid4()))
            article_url = row.get("url", SOURCE_URL)
            title = row.get("title", "")
            text = row.get("text", "")

            sentences = _extract_sentences(text)
            for sent_idx, sent in enumerate(sentences):
                record = {
                    "source_name": "wikipedia_te",
                    "source_doc_id": f"wiki_{article_id}_s{sent_idx}",
                    "source_url": article_url,
                    "license_tag": LICENSE_TAG,
                    "pull_timestamp_utc": pull_ts,
                    "text_raw": sent,
                    "script_hint": "telugu",
                    "lang_hint": "te",
                    "row_hash": _row_hash(sent),
                    "article_title": title,
                }
                fout.write(json.dumps(record, ensure_ascii=False) + "\n")
                sentences_written += 1

            articles_processed += 1
            if articles_processed % 10000 == 0:
                print(f"  {articles_processed:,} articles, {sentences_written:,} sentences ...")

    manifest = {
        "run_id": str(uuid.uuid4()),
        "source_name": "wikipedia_te",
        "pull_timestamp_utc": pull_ts,
        "record_count": sentences_written,
        "output_file": str(output_file),
        "license_tag": LICENSE_TAG,
        "articles_processed": articles_processed,
        "note": "Telugu script only. Roman pairs generated by romanize_rules.py.",
    }
    with manifest_file.open("w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    print(f"Done: {articles_processed:,} articles -> {sentences_written:,} sentences -> {output_file}")


if __name__ == "__main__":
    main()
