import hashlib
import json
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

from datasets import load_dataset

SOURCE_URL = "https://huggingface.co/datasets/ai4bharat/samanantar"
LICENSE_TAG = "CC-BY-NC-4.0"
TAKEDOWN_CONTACT = "ai4bharat@iisc.ac.in"

TELUGU_START = 0x0C00
TELUGU_END = 0x0C7F
MIN_CHARS = 15
MAX_CHARS = 300
MAX_ROWS = 300_000


def _is_mostly_telugu(text: str, threshold: float = 0.3) -> bool:
    if not text:
        return False
    te = sum(1 for c in text if TELUGU_START <= ord(c) <= TELUGU_END)
    return te / len(text) >= threshold


def _row_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def main() -> None:
    today = datetime.now(tz=timezone.utc).strftime("%Y%m%d")
    pull_ts = datetime.now(tz=timezone.utc).isoformat()
    output_file = Path(f"data/raw/samanantar_{today}.jsonl")
    manifest_file = Path(f"data/manifests/samanantar_{today}_manifest.json")

    if output_file.exists():
        print(f"Snapshot {output_file} already exists — raw/ is immutable, skipping.")
        sys.exit(0)

    output_file.parent.mkdir(parents=True, exist_ok=True)
    manifest_file.parent.mkdir(parents=True, exist_ok=True)

    print(f"Loading Samanantar Telugu via datasets library (max {MAX_ROWS:,}) ...")
    ds = load_dataset("ai4bharat/samanantar", "te", split="train", streaming=True)

    written = 0
    with output_file.open("w", encoding="utf-8") as fout:
        for row in ds:
            if written >= MAX_ROWS:
                break

            telugu = (row.get("tgt") or "").strip()

            if not (MIN_CHARS <= len(telugu) <= MAX_CHARS):
                continue
            if not _is_mostly_telugu(telugu):
                continue

            record = {
                "source_name": "samanantar",
                "source_doc_id": f"sam_te_{written}",
                "source_url": SOURCE_URL,
                "license_tag": LICENSE_TAG,
                "pull_timestamp_utc": pull_ts,
                "text_raw": telugu,
                "script_hint": "telugu",
                "lang_hint": "te",
                "row_hash": _row_hash(telugu),
                "takedown_contact": TAKEDOWN_CONTACT,
            }
            fout.write(json.dumps(record, ensure_ascii=False) + "\n")
            written += 1

            if written % 50000 == 0:
                print(f"  {written:,} sentences ...")

    manifest = {
        "run_id": str(uuid.uuid4()),
        "source_name": "samanantar",
        "pull_timestamp_utc": pull_ts,
        "record_count": written,
        "output_file": str(output_file),
        "license_tag": LICENSE_TAG,
        "takedown_contact": TAKEDOWN_CONTACT,
        "note": "Telugu side only. Roman pairs generated by romanize_rules.py.",
    }
    with manifest_file.open("w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    print(f"Done: {written:,} sentences -> {output_file}")


if __name__ == "__main__":
    main()
