model:
  name: google/byt5-small
  max_input_length: 128
  max_target_length: 128

data:
  train_file: data/processed_v3/train.jsonl
  val_file:   data/processed_v3/val.jsonl
  roman_field: roman_text
  telugu_field: telugu_text

training:
  output_dir: train/checkpoints_v3
  seed: 42
  num_train_epochs: 1
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  learning_rate: 5.0e-4
  warmup_steps: 500
  weight_decay: 0.01
  fp16: false
  bf16: true
  gradient_checkpointing: false
  max_grad_norm: 1.0
  evaluation_strategy: epoch
  save_strategy: steps
  save_steps: 10000
  save_total_limit: 2
  load_best_model_at_end: false
  logging_steps: 200
  dataloader_num_workers: 0
  gradient_accumulation_steps: 1
  predict_with_generate: true
  generation_max_length: 128
